### ISSUE TITLE
Screen goes blank when editing shaders in the Basic Shaders example 

### ISSUE THREAD

**Issue by offbeat-dev** [Tresjs/playground#38]
Hi Alvaro,

First of all thank you very much for all your work in Tresjs. It's great! 

I have been playing around with the playground examples and noticed that hot reload doesn't work when updating a shader file in the  Basic Shaders example. 
vite-plugin-glsl seems to work fine on a separate vite project, so I am not sure if this issue has to do with TresJS or Nuxt or the glsl plugin. I was wondering if you have any idea on what could be causing the screen to go blank when editing shader files. If I find a solution I'll make sure to let you know as well. 

Thank you, 

Paulo

**Comment by alvarosabu** [comment]
Hi, @offbeat-dev. Thanks for the feedback 😊 

We are aware, HMR has been really tricky over the development of TresJS, after v2 since we changed to a custom renderer the HMR is quite broken and difficult to make right. I can confirm that it is more likely something about Tresjs rather than the glsl plugin or Nuxt

We have an issue open at the core package https://github.com/Tresjs/tres/issues/271 to fix the HMR

Sorry about the inconvenience. 🙏🏻

**Comment by offbeat-dev** [comment]
No worries @alvarosabu!
I'll keep an eye for any updates on [https://github.com/Tresjs/tres/issues/271](https://github.com/Tresjs/tres/issues/271) regarding the HMR issue.
Thank you very much for the prompt reply!

**Comment by alvarosabu** [comment]
@offbeat-dev I have some updates for you. I kinda managed to make the HMR work, but things like OrbitControls that depend on `provide/inject` gets broken.

https://github.com/Tresjs/playground/assets/4699008/a6d23ee9-5a7e-4de2-82a4-614f749155c6
